<div class="stage-slide-out-div">
	<a class="stage-handle"></a>
	<form id="settings">
		<p>
			<label><h3>View mode:</h3></label>
			<input type="radio" id="view-both" name="view" value="both" checked="true">Show Word Cloud and Feed</input><br/>
			<input type="radio" id="view-feed" name="view" value="feed">Show only the live Feed</input><br/>
			<input type="radio" id="view-cloud" name="view" value="cloud">Show only the Word Cloud</input><br/>
		</p><p>
			<input type="submit" name="settings-submit" id="settings-submit" value="Save Settings"/><br/><br/>
		</p>
	</form>
</div>
 
