<div id="helpDialog" title="Help | Sending love via email" style = "display: none;">
    <p>Sending love via email is great!  </p>
    <p>To email your company sendlove, you need to:</p>
    <ol>
        <li>Address your email to: <?php echo COMPANY_NAME; ?>@sendlove.us</li>
        <li>Add a CC (carbon-copy) of the email to your intended recipient.</li>
        <li>Use the subject field for your love message</li>
    </ol>
    <h3>Tips</h3>
    <ul>
        <li>The love message cannot exceed 250 characters.</li>
        <li>The recipient must be an active member of this sendlove</li>
        <li>You can send the same love to multiple people, just carbon-copy additional recipients!</li>
        <li>Send quiet love by including (quiet) at the start of the email subject</li>
    </ul>
	
</div>