<div id="splashscreen" title="Hello and Welcome <?php echo($front->getCompany()->getName()); ?>!" style = "display: none;">
	Get started now by personalizing your LoveMachine ...<br /><br />
	Go to the <a href="/admin/" title="Administration">Admin area</a> and:<br />
	<ul>
		<li>Invite users to join your LoveMachine now.</li>
		<li>Upload your company logo.</li>
		<li>Change the appearance of your page with custom colors and fonts.</li>
		<li>Customize love notifications.</li>
		<li>And much more!</li>
	</ul>
	Get Started now! Once new users have joined you can send and receive Love immediately!
	<br /><br />
	<label for="stopsplash">Don't show this screen again.</label>
</div>
