<div id="content-box" class="ui-widget-content ui-corner-all">
    <div id="leftBorder"></div>
    <div id="contentBody">
        <div id="contentBodyLeft">
            <div class="hTitle hTitle2">Login to SendLove</div><br/>
            <div class="clear"></div>
            <div id="security-notice">
                <span id="notice-title">Note:</span><br/>
                <span>Security is important! To keep your information safe, we need you to log into your Control Panel separately
                 from your SendLove. You can do so here. 
                <br/>
                <br/>
                 In addition, to prevent a security breach, the system will log you out after ten minutes. If you need more time,
                 just log in again and keep going!</span>
            </div>

            <div id="contentBodyFormLeft">
                <?php if ($this->error) { ?>
                    <div class="ui-widget" style="width: 300px;">
                        <div style="padding: 0pt 0.7em;" class="ui-state-error ui-corner-all"> 
                            <p style="line-height:100%;color:#CD0A0A;margin:0;"><span style="float: left; margin-right: 0.3em;" class="ui-icon ui-icon-alert"></span> 
                            <strong>The following errors occured:</strong></p>
                            <p><?php echo $this->message ?></p>
                        </div>
                    </div>
                <?php } ?>

                <form id="loginForm" method="post" action="<?php echo $this->baseUrl() ?>/login">
                    <fieldset class="fieldset">

                        <label class="label" for="username">Username</label><br/>
                        <input class="input" type="text" id="username" name="username" value="" />
                        <input type="submit" class="button" name="login" value="Login" id="login" /><br/>

                        <label class="label" for="password">Password</label><br/>
                        <input class="input" type="password" id="password" name="password" value="" />

                    </fieldset>
                </form>
            </div>

            <div id="contentBodyFormRight">
				<!-- Google Login deactivated
                <div id="errorHolderRight"></div>
                <form id="GoogleLoginForm" method="post" action="login.php">
                    <fieldset class="fieldset">

                        <label for="googleLogin">Google Login</label><br/>
                        <input type="text" id="googleLogin" class="input google" name="googleLogin" value="" />
                        <input type="submit" class="button" name="gLogin" id="gLogin" value="Google Login" />

                    </fieldset>
                </form>
				-->
            </div>
            <div class="clear"></div>
        </div>

        <div id="contentBodyRight">
            <div id="forgot-block">
				<div>
		            <h3>Forgot your password?</h3>
		            <a href="/love/forgot.php">Recover it here</a>
				</div>
				<div>
					<h3>Need a login?</h3>
					<a href="/love/login.php" id="ping_admin">Send a message to the admin</a>
				</div>
				<div>
					<h3>Want a SendLove?</h3>
					<a href="http://trial.sendlove.us/trial/">Get your own SendLove</a>
				</div>
            </div>
        </div>
        <div class="clear"></div>

    </div>
    <div id="rightBorder"></div>
<div class="clear"></div>
