<div>
	<table class="common-table report-love-table">
		<thead>	
			<tr id="report-love-table-heading" class="table-hdng">
				<td rel="username" class="col1">Username</td>
				<td rel="nickname" class="col2">Nickname</td>
				<td rel="sent" class="col3">Love Sent</td>
				<td rel="received" class="col4">Total Love</td>
				<td rel="received" class="col5">Total Value</td>
			</tr>
		</thead>
		<tbody id="report-love-tbody">
		</tbody>
	</table>
	<div class="export-div">
		<input type="button" class="button" id="export-report-love" value="Export Report"/>
	</div>	
</div>
