<p><?php echo $this->creator_nickname ?> (<?php echo $this->creator_email ?>) has created an account for you to join <?php echo $this->company_name ?> on SendLove.</p>
<p><a href="<?php echo $this->url ?>" title="Love Login">Click here to login.</a></p>
<p>Your credentials:<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Username: <?php echo $this->user_username ?><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Password: <?php echo $this->user_password ?></p>
<p>Love,<br />
SendLove</p>